In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print("one dimensional array:",a)

one dimensional array: [1 2 3 4 5]


In [2]:
import numpy as np
b=np.array([[10,20,30],[50,60,70]])
print("two dimensional array:",b)

two dimensional array: [[10 20 30]
 [50 60 70]]


In [3]:
import numpy as np
x=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("three dimensional array:",x)

three dimensional array: [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
import numpy as np
y=np.zeros((3,5))
print("\n array with all zeros:\n",y)


 array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
n=np.random.random((2,2))
print("\n Random values:\n",n)


 Random values:
 [[0.75350766 0.33334406]
 [0.84599248 0.1113054 ]]


In [7]:
import numpy as np
m=np.arange(3,20,3)
print("\n Sequence array \n",m)


 Sequence array 
 [ 3  6  9 12 15 18]


In [8]:
import numpy as np
f=np.array([[1,2,3,4],[7,8,9,6],[0,11,50,32]])
g=f.reshape(4,3)
print("\n original array:\n",f)
print("\n reshaped array:\n",g)


 original array:
 [[ 1  2  3  4]
 [ 7  8  9  6]
 [ 0 11 50 32]]

 reshaped array:
 [[ 1  2  3]
 [ 4  7  8]
 [ 9  6  0]
 [11 50 32]]


In [9]:
import numpy as np
p=np.array([[1,2,3],[4,5,6]])
flat=p.flatten()
print("\n original array:\n",p)
print("flattened array:",flat)


 original array:
 [[1 2 3]
 [4 5 6]]
flattened array: [1 2 3 4 5 6]


In [14]:
print("\n No.Of.Dimensions:\n",p.ndim)


 No.Of.Dimensions:
 2


In [17]:
import numpy as np
o=np.array([5,6,7,8,9,0])
print("no.of.dimensions:",o.ndim)

no.of.dimensions: 1


In [23]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("no.of dimensions:",a.ndim)

no.of dimensions: 3


In [24]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print("shape of the array:",b.shape)

shape of the array: (2, 3)


In [25]:
print("\n Array element type:",b.dtype)


 Array element type: int64


In [26]:
size=len(b)
print("\n size of the array:\n",size)


 size of the array:
 2


In [31]:
import numpy as np
c=np.array([1,2,3,4])
size=len(c)
print("size of array:",c.size)

size of array: 4


In [1]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64
