In [1]:
import numpy as np
x=np.array([1,6,2,7,6,4])
x1=np.where(x==6)
print(x1)

(array([1, 4]),)


In [2]:
x2=np.where(x==7)
print(x2)

(array([3]),)


In [3]:
y=np.where(x%2==0)
print(y)

(array([1, 2, 4, 5]),)


In [6]:
p=np.where(x%3==1)
print(p)

(array([0, 3, 5]),)


In [8]:
#inserting an array in a position 
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [9]:
#sorting of 1D array
import numpy as np
a=np.array([9,5,2,7,6,4])
print(np.sort(a))

[2 4 5 6 7 9]


In [11]:
#for 2D array
a=([[7,4,9],[9,1,4]])
print(np.sort(a))

[[4 7 9]
 [1 4 9]]


In [13]:
#boolean indexing
import numpy as np
arr=np.array([31,78,69,100])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[ 78 100]


In [16]:
#filter
filter_arr=arr<70
print(filter_arr)


[ True False  True False]
